package constants

const (
	ENV_FILE_PATH           = "ENV_FILE_PATH"
	ENV_ADDRESSES           = "ADDRESSES"
	ENV_RPC_ENDPOINT        = "RPC_ENDPOINT"
	ENV_CONCURRENCY         = "CONCURRENCY"
	ENV_CHUNK_SIZE          = "CHUNK_SIZE"
	ENV_MAX_RETRIES         = "MAX_RETRIES"
	ENV_DEFAULT_START_BLOCK = "DEFAULT_START_BLOCK"
	ENV_DEFAULT_END_BLOCK   = "DEFAULT_END_BLOCK"
)
